# Generated by Django 5.2.3 on 2025-06-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('asin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('date_read', models.DateField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional rating from 1 to 5', null=True)),
            ],
        ),
    ]
