# Generated by Django 5.2.3 on 2025-06-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='shelfBook',
        ),
    ]
