# Generated by Django 5.2.3 on 2025-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_rename_book_shelfbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfbook',
            name='amazon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfbook',
            name='googlebooks_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfbook',
            name='openlibrary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfbook',
            name='user',
            field=models.CharField(default='todd', max_length=100),
        ),
    ]
