# Generated by Django 5.2.3 on 2025-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_shelfbook_amazon_url_shelfbook_googlebooks_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfbook',
            name='amazon_search_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfbook',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
