# Generated by Django 5.2.3 on 2025-06-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_shelfbook_amazon_search_url_shelfbook_date_acquired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfbook',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
