# Generated by Django 5.2.3 on 2025-06-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_asin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='amazon_search_url',
            field=models.URLField(blank=True),
        ),
    ]
